### ISSUE TITLE
./build.sh not downloading nuget.exe correctly

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.TravisCI#10]
When trying to run the build on my Mac after an initial clone, I get the following:

![image](https://user-images.githubusercontent.com/1271146/56488447-48487d80-64d6-11e9-967d-9c5428d45b8c.png)

After a tweak to the build.sh, I can make the build work:

![image](https://user-images.githubusercontent.com/1271146/56488465-54ccd600-64d6-11e9-81c4-7ce60ab24dba.png)

I can send a PR for this change, but wanted to make sure you weren't gunning for something else here.

**Comment by RLittlesII** [comment]
@gep13 This is because all my Mac's have global cake config.  Please feel free to submit the PR.  One question.  I have been solving this with a `cake.config` file recently.  Is there a better way?

**Comment by gep13** [comment]
I am not sure I follow how the cake.config file comes into play here. The bootstrapper doesn’t currently know about those configuration options.

**Comment by RLittlesII** [comment]
@gep13 I got this cleaned up.  Thanks for reporting this.

**Comment by gep13** [comment]
@RLittlesII great news, thanks!
