### ISSUE TITLE
Updaet Cake to v0.35.0

### ISSUE THREAD

**Issue by RLittlesII** [cake-contrib/Cake.TravisCI#15]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Addin version used:
* Cake Version used:
* Operating System:

**Comment by pascalberger** [comment]
@RLittlesII Do you have a specific reason to build against Cake 0.35.0? General guidance is to build against earliest version without breaking API changes, which currently is 0.33.0 (see [Guidelines](https://github.com/cake-contrib/Home/blob/master/Guidelines.md#supported-cake-version)).
